# Generated by Django 5.1.2 on 2024-10-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent',
            old_name='total_sent',
            new_name='totle_sent',
        ),
    ]
